[workspace]
members = [
    "crates/wudo-core",
    "crates/wudo-protocol",
    "crates/wudo-store",
    "crates/wudod",
    "crates/wudo-web",
    "crates/wudo-cli",
    "ui/wudo-ui",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"
