CREATE TABLE users (id BLOB PRIMARY KEY NOT NULL CHECK(length(id)=16), name TEXT NOT NULL UNIQUE CHECK(length(CAST(name AS BLOB)) BETWEEN 1 AND 64), label TEXT NOT NULL CHECK(length(CAST(label AS BLOB)) BETWEEN 1 AND 128)) STRICT;
PRAGMA application_id = 1465205839;
